name: Dotnet Build
description: Build FDD and SCD
inputs:
  project-path:
    required: true
  rid:
    required: true
runs:
  using: composite
  steps:
    # Framework-Dependent Build (Linux/macOS)
    - name: Build FDD (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        dotnet publish ${{ inputs.project-path }} \
          -c Release \
          -o out/fdd-${{ inputs.rid }} \
          -r ${{ inputs.rid }} \
          --no-self-contained \
          /p:Version=${{ env.VERSION }} \
          /p:AssemblyVersion=${{ env.VERSION }} \
          /p:FileVersion=${{ env.VERSION }} \
          /p:InformationalVersion=${{ env.INFO_VERSION }}
      shell: bash

    # Framework-Dependent Build (Windows)
    - name: Build FDD (Windows)
      if: runner.os == 'Windows'
      run: >
        dotnet publish ${{ inputs.project-path }} -c Release -o out/fdd-${{ inputs.rid }} -r ${{ inputs.rid }} --no-self-contained /p:Version=${{ env.VERSION }} /p:AssemblyVersion=${{ env.VERSION }} /p:FileVersion=${{ env.VERSION }} /p:InformationalVersion=${{ env.INFO_VERSION }}
      shell: pwsh

    # Self-Contained Build (Linux/macOS)
    - name: Build SCD (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        dotnet publish ${{ inputs.project-path }} \
          -c Release \
          -o out/scd-${{ inputs.rid }} \
          -r ${{ inputs.rid }} \
          --self-contained true \
          /p:Version=${{ env.VERSION }} \
          /p:AssemblyVersion=${{ env.VERSION }} \
          /p:FileVersion=${{ env.VERSION }} \
          /p:InformationalVersion=${{ env.INFO_VERSION }}
      shell: bash

    # Self-Contained Build (Windows)
    - name: Build SCD (Windows)
      if: runner.os == 'Windows'
      run: >
        dotnet publish ${{ inputs.project-path }} -c Release -o out/scd-${{ inputs.rid }} -r ${{ inputs.rid }} --self-contained true /p:Version=${{ env.VERSION }} /p:AssemblyVersion=${{ env.VERSION }} /p:FileVersion=${{ env.VERSION }} /p:InformationalVersion=${{ env.INFO_VERSION }}
      shell: pwsh
